CREATE TABLE "courses" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"video" text NOT NULL,
	"thumbnail" text,
	"age_group" text NOT NULL,
	"category" text NOT NULL,
	"difficulty" text NOT NULL,
	"duration" text NOT NULL,
	"duration_minutes" integer DEFAULT 0 NOT NULL,
	"price" text DEFAULT 'FREE' NOT NULL,
	"skills" text[] DEFAULT '{}' NOT NULL,
	"prerequisites" text[] DEFAULT '{}' NOT NULL,
	"learning_objectives" text[] DEFAULT '{}' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"instructor" jsonb,
	"analytics" jsonb DEFAULT '{"enrollments":0,"completions":0,"views":0,"averageRating":0,"totalRatings":0}'::jsonb NOT NULL,
	"is_published" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "packages" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"subtitle" text,
	"price" text DEFAULT 'FREE' NOT NULL,
	"original_price" text,
	"savings" text,
	"icon" text DEFAULT '🎓' NOT NULL,
	"includes" text[] DEFAULT '{}' NOT NULL,
	"features" text[] DEFAULT '{}' NOT NULL,
	"age_groups" text[] DEFAULT '{}' NOT NULL,
	"course_ids" text[] DEFAULT '{}' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"popular" boolean DEFAULT false NOT NULL,
	"target_audience" text DEFAULT 'families' NOT NULL,
	"benefits" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"content" jsonb,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
