-- ============================================================================
-- Phase 1 — Supabase-specific SQL (NOT generated by drizzle-kit).
-- Run this in the Supabase SQL Editor AFTER `npm run db:migrate`
-- (which creates the public.profiles table).
--
-- It does three things:
--   1. Links profiles.id → auth.users.id (FK, cascade delete)
--   2. Enables Row Level Security so users only touch their own profile
--   3. Auto-creates a profile row whenever a new auth user signs up
-- ============================================================================

-- 1. Foreign key to auth.users (drizzle can't reference the auth schema) ------
alter table public.profiles
  drop constraint if exists profiles_id_fkey;
alter table public.profiles
  add constraint profiles_id_fkey
  foreign key (id) references auth.users (id) on delete cascade;

-- 2. Row Level Security -------------------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- No INSERT/DELETE policy on purpose: rows are created by the trigger below
-- (security definer) and removed via the auth.users cascade.

-- 3. Auto-create profile on signup -------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, phone, user_type, age_group)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', 'Learner'),
    new.raw_user_meta_data ->> 'phone',
    coalesce(new.raw_user_meta_data ->> 'user_type', 'parent'),
    new.raw_user_meta_data ->> 'age_group'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 4. Keep updated_at fresh ----------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();
